apiVersion: actions.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool-sample
spec:
  repositoryName: github-actions-controller-ci
  template:
    image: actions-runner:kindtest
    imagePullPolicy: Never
    env:
    - name: EXTEND_DURATION
      value: "30s"
