
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - actions.cybozu.com
  resources:
  - runnerpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.cybozu.com
  resources:
  - runnerpools/status
  verbs:
  - get
  - patch
  - update
