# permissions for end users to view runnerpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerpool-viewer-role
rules:
- apiGroups:
  - actions.cybozu.com
  resources:
  - runnerpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.cybozu.com
  resources:
  - runnerpools/status
  verbs:
  - get
