apiVersion: actions.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool-sample
spec:
  # TODO
  repositoryName: hostrunner-poc
  replicas: 3
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      containers:
      - name: runner
        image: runner:latest
        # TODO
        imagePullPolicy: Never

