apiVersion: actions.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool-sample
spec:
  repositoryName: hostrunner-poc
  template:
    spec:
      containers:
      - name: runner
        image: runner:latest
        imagePullPolicy: Never
