name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: |
          make setup
          make lint
          make test
          make build
  kindtest:
    name: Run test on kind
    runs-on: ubuntu-20.04
    env:
      GITHUB_APP_ID: ${{ secrets.APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
      GITHUB_APP_PRIVATE_KEY_PATH: key.pem
      SLACK_APP_TOKEN: dummy
      SLACK_BOT_TOKEN: dummy
      SLACK_WEBHOOK_URL: dummy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: |
          echo ${GITHUB_APP_PRIVATE_KEY} > ${GITHUB_APP_PRIVATE_KEY_PATH}
          make setup
          make images
          make start-kind
          make load
          make prepare
          make kindtest
